from dataclasses import dataclass


@dataclass
class ToolBuildRequest:
    """
    Describes a capability that AURA wants to build.
    """

    capability: str
    reason: str


@dataclass
class GeneratedTool:
    """
    Represents a tool generated by the Tool Builder.

    At this stage, the builder only creates the specification.
    It does NOT execute generated code.
    """

    name: str
    description: str
    purpose: str
    inputs: list[str]
    outputs: list[str]


class ToolBuilder:
    """
    Designs tools needed to satisfy capability gaps.

    This is intentionally a specification-only builder.

    Later versions will:
    1. Generate source code.
    2. Generate tests.
    3. Validate the generated tool.
    4. Execute it inside a sandbox.
    5. Register successful tools.
    """

    def build(
        self,
        request: ToolBuildRequest,
    ) -> GeneratedTool:
        """
        Create a tool specification for a missing capability.
        """

        capability = request.capability.strip()

        if not capability:
            raise ValueError(
                "Capability cannot be empty."
            )

        if capability == "experiment_design":

            return GeneratedTool(
                name="experiment_design",
                description=(
                    "Design controlled research experiments "
                    "from a research question and research plan."
                ),
                purpose=(
                    "Generate experimental variables, conditions, "
                    "metrics, controls, and evaluation procedures."
                ),
                inputs=[
                    "research_question",
                    "hypotheses",
                    "objectives",
                ],
                outputs=[
                    "variables",
                    "experimental_conditions",
                    "metrics",
                    "controls",
                    "procedure",
                ],
            )

        return GeneratedTool(
            name=capability,
            description=(
                f"Tool providing the '{capability}' capability."
            ),
            purpose=request.reason,
            inputs=[
                "research_context",
            ],
            outputs=[
                "structured_result",
            ],
        )
